version: '2.1'
services:
    btcbox:
        image: lncm/bitcoind:0.17.1-alpine-arm
        volumes:
            - /home/lncm/bitcoin:/home/bitcoin/.bitcoin
            - /home/lncm/bitcoin:/root/.bitcoin
        ports:
            - "8332:8332"
            - "8333:8333"
            - "28332:28332"
            - "28333:28333"
        environment:
            - BITCOINRPCHOST=btcbox
            - BITCOINRPCUSER=RANDOMUSER
            - BITCOINRPCPASS=RANDOMPASS
        networks:
            localnet:
                ipv4_address: 172.16.88.8
    lndbox:
        image: lncm/lnd:latest
        volumes:
            - /home/lncm/lnd:/root/.lnd
        ports:
            - "9735:9735"
        depends_on:
            - btcbox
        restart: on-failure
        networks:
            localnet:
                ipv4_address: 172.16.88.88
networks:
    localnet:
        driver: bridge
        ipam:
            driver: default
            config:
                -
                    subnet: 172.16.88.0/24

